### ISSUE TITLE
Available of HVU dataset?

### ISSUE THREAD

**Issue by danieljf24** [holistic-video-understanding/HVU-Dataset#1]
Hi @alidiba67   Thanks for creating the HVU dataset. I am wondering when the dataset will be available?

**Comment by alidiba67** [comment]
Hi, It is released now. Sorry for the delay but we had to to some more validation and human verification rounds to guarantee a clean dataset.

**Comment by alidiba67** [comment]
Hi, Sorry for delay. The dataset is released now. We had to go for some more human verification rounds to guarantee a clean dataset.
