### ISSUE TITLE
The form for missing videos is invalid

### ISSUE THREAD

**Issue by JoeHEZHAO** [holistic-video-understanding/HVU-Dataset#11]
Hi all

The form link for ``Accessing Missing Videos and Test Videos'' is invalid now.

Is it possible for you to update it?

He

**Comment by MohsenFayyaz89** [comment]
Hi,

I checked the form and it is available and functional. Please use the form that is provided in the README.md

**Comment by JoeHEZHAO** [comment]
True. Probably it was a network issue yesterday. I filled the form. Thanks!
