### ISSUE TITLE
Mapping of tags to categories

### ISSUE THREAD

**Issue by rhsieh91** [holistic-video-understanding/HVU-Dataset#2]
I can't tell which tags in the train/val labels map to which categories. Would you be able to publish a mapping that matches tags to categories? Thanks!

**Comment by alidiba67** [comment]
Hi, Check [**HVU_Tags_Categories_V1.0.csv**](https://github.com/holistic-video-understanding/HVU-Dataset/blob/master/HVU_Tags_Categories_V1.0.csv) file. There is mapping between tags and corresponding category.

**Comment by rhsieh91** [comment]
Sorry didn’t see that the mapping file already exists.
