### ISSUE TITLE
Some downloaded files only 252 Bytes

### ISSUE THREAD

**Issue by NikhilBartwal** [holistic-video-understanding/HVU-Dataset#3]
I was working to integrate the HVU Dataset to Tensorflow Datasets. I tried running this script [https://github.com/holistic-video-understanding/HVU-Downloader/blob/master/HVU_download.py](url) both directly from the terminal as well as by using the code in my Kaggle Notebook and what happens is that some files **(almost ~10%)** are not properly downloaded and are around 252 Bytes each only. 
On the other hand, if i use the script code for the individual video IDs that were not downloaded properly, there is no issue.

What do you think could be causing this?
I think it has something to do with the **joblib.parallel** library which was used for parallelisation in the script.
I'm attaching a screenshot of my Kaggle Notebook output showcasing the improperly downloaded files.

![image](https://user-images.githubusercontent.com/42388668/88689607-4d07d280-d118-11ea-9921-0f9659fff01c.png)

**Comment by bhack** [comment]
@NikhilBartwal Can you try with `python3 HVU_download.py -n -1`?

**Comment by alidiba67** [comment]
@NikhilBartwal Did you try the downloader with the latest version of youtube-dl? I have experienced same issue
sometimes with some of the youtube videos. Unfortunately couldn't find any solution yet.

**Comment by bhack** [comment]
Yes try also with `pip install --upgrade  youtube-dl` it seems that the issue disappeared with new versions.

EDIT tested with:
`youtube-dl-2020.7.28`

**Comment by bhack** [comment]
I think that there is still some issue with all these parallel default job.
Also I don't think that it is useful to run multiple parallel `ffmpeg` for video segments extraction.
Currently I am testing with `-n 2` param

**Comment by NikhilBartwal** [comment]
@bhack @alidiba67 I have found what the problem was and what the solution is.
The **Parallel** method of the **joblib** library used the 'Loky' backend by default which is a multi process system and therefore, does not allow, by default, the various processes to access the common resource. The solution was to pass the **require = 'sharedmem'** argument along with n_jobs in the parallel function.

Another piece of optimization, instead of using the ffmpeg terminal command use [this](https://stackoverflow.com/questions/37317140/cutting-out-a-portion-of-video-python). Using this instead of the one in script, gives a speed-up of around 40%

**Comment by NikhilBartwal** [comment]
@bhack Using two n_jobs, the dataset would take ages to be download. Try segmenting the videos moviepy library. It will give you a pretty big speedup

**Comment by bhack** [comment]
@NikhilBartwal thanks. I think that you can send a PR to https://github.com/holistic-video-understanding/HVU-Downloader.
What I meant  It is that could be nice to separate downloads from ffmpeg. It is slow cause the download and segment extraction it is on the same method. 
Download will benefit from parallelism but I don't think on ffmpeg or ffmpeg_extract_subclip.

**Comment by NikhilBartwal** [comment]
@bhack I would send a PR soon. Just so we are on the same page, you think it would be nice to download the videos using parallelism and then simply segment the videos after downloading?

**Comment by bhack** [comment]
What I meant is that in https://github.com/holistic-video-understanding/HVU-Downloader/blob/master/HVU_download.py#L26 we have the `youtube-dl` and `ffmpeg` in the same job.
I don't know if it is better to have many `ffmpeg` with `-threads 1` with the same number of download jobs as we currently have or it is better to have few or 1 `ffmpeg` instances with unset threads.

**Comment by NikhilBartwal** [comment]
@bhack I guess I will tinker around with it and then see which is the most optimal solution. Thanks!

**Comment by bhack** [comment]
What I think it is that probably the most optimal solution, in the case we have not so much CPUs is to parallel download and rencode with ffmpeg hw acceleration params:
https://trac.ffmpeg.org/wiki/HWAccelIntro
https://trac.ffmpeg.org/wiki/Hardware/QuickSync

**Comment by NikhilBartwal** [comment]
@bhack Thanks for such insightful replies. 
ffmpeg with hw acceleration params require the nvidia **nvec** library to be installed, customized specifically for ffmpeg. Even after using that, the speed-up which it provided was not worth the trouble.
I implemented your idea of parallel download with all available CPUs and segmenting videos using the moviepy library using only two parallel processes. It gave a speed-up of more than 50% and it keeps on increasing as the number of videos increases.
I have made a PR [here](https://github.com/holistic-video-understanding/HVU-Downloader/pull/2).
Thanks for the help!

**Comment by bhack** [comment]
@NikhilBartwal yes hwaccell is of course less portable but often I had an huge speed-up if correctly parametrized. 

Thanks for benchmarking download/cut-encoding jobs allocation.

**Comment by NikhilBartwal** [comment]
@bhack The download and pre-processing were taking ages. Now that it has been optimized, I'll continue with the TFDS dataset.
@MohsenFayyaz89 @alidiba67 It would be great if you could review [the](https://github.com/holistic-video-understanding/HVU-Downloader/pull/2) PR
