### ISSUE TITLE
Some videos can not be downloaded

### ISSUE THREAD

**Issue by cs2r** [holistic-video-understanding/HVU-Dataset#4]
I try to download the dataset videos but when the downloading finished I found that some videos are not downloaded, so is these videos are private or permanently deleted from youtube.

**Comment by MohsenFayyaz89** [comment]
In case you cannot get all of the videos, you can fill the form we recently added [here](https://github.com/holistic-video-understanding/HVU-Dataset#downloading-videos) to obtain the full dataset.
