### ISSUE TITLE
About download dataset

### ISSUE THREAD

**Issue by MinamiKotoka** [holistic-video-understanding/HVU-Dataset#5]
Hi, I'm every interested in your work. Could you provide a trimmed video dataset where the length of each video is 10s? I can not download all the entire videos and trim them because of some limitted of my computer. Thank you very much if you could help me.

**Comment by MohsenFayyaz89** [comment]
Hi, thanks for your interest. Please fill the form we have provided [here](https://github.com/holistic-video-understanding/HVU-Dataset#downloading-videos).

**Comment by MinamiKotoka** [comment]
> Hi, thanks for your interest. Please fill the form we have provided [here](https://github.com/holistic-video-understanding/HVU-Dataset#downloading-videos).

OK, I have submitted it. Look forward your reply, Thank you.

**Comment by MohsenFayyaz89** [comment]
> > Hi, thanks for your interest. Please fill the form we have provided [here](https://github.com/holistic-video-understanding/HVU-Dataset#downloading-videos).
> 
> OK, I have submitted it. Look forward your reply, Thank you.

Sorry, since you have not provided your **affiliation** and your **academic/organization email address** in the form we cannot grant you access to the dataset.

**Comment by MinamiKotoka** [comment]
> > > Hi, thanks for your interest. Please fill the form we have provided [here](https://github.com/holistic-video-understanding/HVU-Dataset#downloading-videos).
> > 
> > 
> > OK, I have submitted it. Look forward your reply, Thank you.
> 
> Sorry, since you have not provided your **affiliation** and your **academic/organization email address** in the form we cannot grant you access to the dataset.

I'm sorry to hear that. Could you show me a example about **affiliation** and **academic/organization email address**? I'm just a student and want your dataset to do research out of interest. Thank you very much if you can reply me.
